using System;
using System.Linq;
using System.Reflection;
using System.Text;
using System.IO;
using UnityEditor;
using UnityEngine;
using Unity.VisualScripting;

public static class ResourcesDataGenerator
{
    private const string path = "Assets/Modules/Resources System/ResourcesData.Generated.cs";

    [MenuItem("Tools/AraragiAriel/Regenerate Resources Data")]
    // [InitializeOnLoadMethod]
    public static void Generate(){
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        var fields = assemblies
            .SelectMany(a => a.GetTypes())
            .Where(t => !t.IsGenericType && !t.IsAbstract)
            .SelectMany(t => t.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
            .Where(f => f.IsDefined(typeof(ResourceAttribute), false))
            .ToList();

        if(fields.Count == 0){
            Debug.LogWarning("[ResourceCodeGenerator] No [Resource] field found");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(path));

        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by ResourceCodeGenerator");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public partial class ResourcesData : ScriptableObject");
        sb.AppendLine("{");

        var tags = Util.EnumList<ResourceAttribute.Tag>();
        foreach(var tag in tags){
            if(!fields.Any(f => f.GetAttribute<ResourceAttribute>().tag == tag))
                continue;
            sb.AppendLine("");

            if(tag == ResourceAttribute.Tag.Editor)
                sb.AppendLine("    #if UNITY_EDITOR");

            sb.AppendLine($"    [Header(\"{tag.ToString().ToUpperInvariant()}\")]");
            foreach(var field in fields){
                var fieldtag = field.GetAttribute<ResourceAttribute>().tag;
                if(fieldtag != tag)
                    continue;
                string name = field.Name;
                string typeName = GetFriendlyTypeName(field.FieldType);
                sb.AppendLine($"    public {typeName} {name};");
            }
            if(tag == ResourceAttribute.Tag.Editor)
                sb.AppendLine("    #endif");
        }

        sb.AppendLine("}");

        File.WriteAllText(path, sb.ToString());
        AssetDatabase.Refresh();
        Debug.Log($"✅ Generated {fields.Count} fields");
    }

    private static string GetFriendlyTypeName(Type type){
        if(!type.IsGenericType)
            return type.FullName.Replace("+", ".");

        string genericName = type.Name.Split('`')[0];
        string args = string.Join(", ", type.GetGenericArguments().Select(GetFriendlyTypeName));
        return $"{type.Namespace}.{genericName}<{args}>";
    }
}
