// Auto-generated by ResourceCodeGenerator
using UnityEngine;

public partial class ResourcesData : ScriptableObject
{

    [Header("DEMO")]
    public System.Boolean demo;

    [Header("DATA")]
    public ColorTagsData colorTags;
    public ScenePersistentData scenePersistentData;
    public UIDs uidsData;
    public LocalizationData localizationData;
    public CurrenciesData currenciesData;
    public CurrentSave currentSave;
    public StatsData statsData;
    public UpgradesData upgradesData;

    [Header("OPTIONS")]
    public GameSettingsData gameSettings;

    [Header("PREFAB")]
    public AudioSourceManager audioSourcePrefab;
    public AfterEffect afterEffect;
    public Popup popup;
    public UnityEngine.GameObject spriteShadow;

    [Header("UI")]
    public ConfirmationBox confirmationBox;

    #if UNITY_EDITOR
    [Header("EDITOR")]
    public EditorPreferencesData editorPreferences;
    public StatsOffsetData offsetData;
    #endif
}
